import { useState } from "react";

interface Searchable {
  authors: string[];
  pages: string[];
  label: string;
  title: string;
}

export const useBookshelf = () => {
  const [indexEntries] = useState<Searchable[]>([
    {
      authors: ["Robert Nystrom"],
      pages: ["274"],
      label: "abstraction",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["157"],
      label: "abstract syntax tree",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["56"],
      label: "Ace of Base",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["45"],
      label: "Achievements class",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["114"],
      label: "Actor class",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["118"],
      label: "Actor class: buffered slap",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["121"],
      label: "Actor class: static buffer offset",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["250"],
      label: "actor model",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["123"],
      label: "Ada Lovelace",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["158"],
      label: "AdditionExpression class",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["245"],
      label: "aggregation",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["26", "87", "104"],
      label: "AI",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["276"],
      label: "AIComponent class",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["283"],
      label: "AIComponent class: hot and cold fields",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["284"],
      label: "AIComponent class: split out cold fields",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["312", "314"],
      label: "algorithmic complexity",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["See amortized complexity"],
      label: "algorithmic complexity: amortized",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["39", "201", "206"],
      label: "allocation",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["244"],
      label: "amortized complexity",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["304"],
      label: "Angular web framework",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["177"],
      label: "ANTLR",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["16"],
      label: "Antoine de Saint-Exupery",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["4"],
      label: "A Pattern Language",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["290"],
      label: "Artemis game engine",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["See AI"],
      label: "artificial intelligence",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["84"],
      label: "aspect-oriented programming",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["See assertion"],
      label: "assert() function",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["83"],
      label: "assertion",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["303"],
      label: "asynchronous processing",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["246"],
      label: "asynchronous-style programming",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["235, 240, 254"],
      label: "Audio class",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["242"],
      label: "Audio class: head and tail pointers",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["235", "240"],
      label: "Audio class: playSound() method",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["245"],
      label: "Audio class: playSound() method: aggregate requests",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["242"],
      label: "Audio class: playSound() method: append to list",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["244"],
      label: "Audio class: playSound() method: ring buffer",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["91"],
      label: "automata theory",
      title: "Game Programming Patterns",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["333"],
      label: "AVL tree",
      title: "Game Programming Patterns",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["15", "16c", "359", "364", "365c"],
      label: "abstract class",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["See coupling"],
      label: "abstract coupling",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["296"],
      label: "abstract coupling: in Observer",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["87"],
      label: "Abstract Factory",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["91"],
      label: "Abstract Factory: extensibility of",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["8"],
      label: "Abstract Factory: in catalog summary",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["51"],
      label: "Abstract Factory: Lexi's use of",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["193"],
      label: "Abstract Factory: used to configure a subsystem",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["88c", "89"],
      label: "Abstract Factory: participant of Abstract Factory",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["See operation"],
      label: "abstract operation",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["144"],
      label: "abstract operation: use to implement Adapter",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["244", "251", "331"],
      label: "abstract syntax tree",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["244c", "331c"],
      label: "abstract syntax tree: class structure for",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["250"],
      label: "abstract syntax tree: constructing in Smalltalk",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["244o"],
      label: "abstract syntax tree: object structure for",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["245c", "245"],
      label: "Abstract Expression: participant of Interpreter",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["153c", "154"],
      label: "Abstraction: participant of Bridge",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["153c, 154"],
      label: "AbstractProduct: participant of Abstract Factory",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["336"],
      label: "accumulating state",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["22", "359"],
      label: "acquaintance",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["23"],
      label: "acquaintance: C++, defined in",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["23"],
      label: "acquaintance: compared with aggregation",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["23"],
      label: "acquaintance: Smalltalk, defined in",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["See command"],
      label: "Action",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["See iterator"],
      label: "active iterator",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["4", "21"],
      label: "Ada",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["141", "141c"],
      label: "Adaptee: participant of Adapter",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["139"],
      label: "Adapter",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["161", "219"],
      label: "Adapter: compared with Bridge",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["184"],
      label: "Adapter: compared with Decorator",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["216"],
      label: "Adapter: compared with Proxy",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["8"],
      label: "Adapter: in catalog summary",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["141", "141c"],
      label: "Adapter: participant of Adapter",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["140"],
      label: "adapter",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["141", "141c"],
      label: "adapter: class adapter",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["141", "141c"],
      label: "adapter: object adapter",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["145"],
      label: "adapter: parameterized",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["See pluggable adapter"],
      label: "adapter: pluggable",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["143", "143c"],
      label: "adapter: two-way",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["179"],
      label: "adorner",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["259", "259c"],
      label: "Aggregate: participant of Iterator",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["257"],
      label: "aggregate object",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["22", "359"],
      label: "aggregation",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["23"],
      label: "aggregation: C++, defined in",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["23"],
      label: "aggregation: compared with acquaintance",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["23"],
      label: "aggregation: notation for",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["23"],
      label: "aggregation: Smalltalk, defined in",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["xiii", "2", "356", "358"],
      label: "Alexander, Christopher",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["24"],
      label: "algorithm: avoiding dependence on",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["326"],
      label: "algorithm: defining steps of",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["317"],
      label: "algorithm: family of",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["327"],
      label: "algorithm: skeleton",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["244co", "343"],
      label: "AlternationExpression",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["249"],
      label: "AlternationExpression: implemented in Smalltalk",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["76"],
      label: "aluminum alloy",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["See also Proxy"],
      label: "Ambassador",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["208"],
      label: "Ambassador: C++ idiom",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["303"],
      label: "AnalogClock",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["353"],
      label: "analysis object model: transforming to design object model",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["361", "See also class", "See also parent"],
      label: "ancestor class",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["xi", "357"],
      label: "Anderson, Bruce",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["253"],
      label: "AndExp",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["303"],
      label: "Andrew Toolkit: use of Observer",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["107", "107c", "223o", "224ci", "231", "325", "325c"],
      label: "Application",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["25"],
      label: "application programs",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["53", "54c", "55c", "157", "233c", "234c"],
      label: "ApplicationWindow",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["42c", "315", "315c", "322"],
      label: "ArrayCompositor",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["183", "183c"],
      label: "ASCII7Stream",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["298"],
      label: "aspect of an object",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["333c"],
      label: "AssignmentNode",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["See also acquaintance", "See also aggregation"],
      label: "associations",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: [
        "Erich Gamma",
        "Richard Helm",
        "Ralph Johnson",
        "John Vlissides",
      ],
      pages: ["364"],
      label: "associations: in OMT",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["16"],
      label: "AAD",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["13", "65"],
      label: "abstract syntax tree",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["28"],
      label: "actual parameter",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["1"],
      label: "adventure",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["221"],
      label: "A Hat Full of Sky",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["algebraic data type"],
      label: "328",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["61"],
      label: "ALGOL 58 language",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["402"],
      label: "ALGOL 60 language",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["428"],
      label: "ALGOL 68 language",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["79"],
      label: "ALGOL language",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["127"],
      label: "ALGOL language: lexical scope",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["145"],
      label: "ALGOL language: syntactic sugar",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["305"],
      label: "Alighieri, Dante",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["213"],
      label: "allocating instances",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["60"],
      label: "alphabet",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["138", "See also Turing machine"],
      label: "a-machine",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["80"],
      label: "ambiguous grammar",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["240"],
      label: "AMC Gremlin",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["399"],
      label: "A Midsummer Night's Dream",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["245"],
      label: "amortized analysis",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["25"],
      label: "and operator",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["170"],
      label: "anonymous function",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["325"],
      label: "ANTLR parser generator",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["602"],
      label: "Appel, Andrew",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["28"],
      label: "argument",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["24"],
      label: "arithmetic operator",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["156"],
      label: "arity",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["15"],
      label: "ARM instruction set",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["23", "356"],
      label: "ASCII",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["61"],
      label: "Ashtadhyayi",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["250"],
      label: "assembler",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["120"],
      label: "associative array",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["25", "81"],
      label: "associativity",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["65", "See abstract syntax tree"],
      label: "AST",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["74"],
      label: "AstPrinter class",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["14"],
      label: "attribute",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Robert Nystrom"],
      pages: ["294"],
      label: "axolotl",
      title: "Crafting Interpreters",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["283-285"],
      label: "abbreviation of names",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["See ADTs"],
      label: "abstract data types",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["104"],
      label: "Abstract Factory pattern",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["340-342"],
      label: "abstraction: access routines for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["See ADTs"],
      label: "abstraction: ADTs for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["136"],
      label: "abstraction: air lock analogy",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["157"],
      label: "abstraction: checklist",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["152", "157"],
      label: "abstraction: classes for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["138"],
      label: "abstraction: cohesion with",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["839"],
      label: "abstraction: complexity, for handling",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["135-136"],
      label: "abstraction: consistent level for class: interfaces",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["89"],
      label: "abstraction: defined",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["138"],
      label: "abstraction: erosion under modification: problem",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["135"],
      label: "abstraction: evaluating",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["136-137"],
      label: "abstraction: exactness goal",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["89-90"],
      label: "abstraction: forming consistently",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["133-134"],
      label: "abstraction: good examples for class interfaces",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["135-138"],
      label: "abstraction: guidelines for creating class interfaces",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["847"],
      label: "abstraction: high-level problem domain terms",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["846"],
      label: "abstraction: implementation structures, low level",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["135-136", "138"],
      label: "abstraction: inconsistent",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["133-138"],
      label: "abstraction: interfaces, goals for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["845-847"],
      label: "abstraction: levels of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["137"],
      label: "abstraction: opposites, pairs of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["846"],
      label: "abstraction: OS level",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["103"],
      label: "abstraction: patterns for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["146"],
      label: "abstraction: placing items in inheritance trees",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["134-135"],
      label: "abstraction: poor example for class interfaces",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["846"],
      label: "problem domain terms, low-level",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["846"],
      label: "abstraction: programming-language level",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["164"],
      label: "abstraction: routines for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["340"],
      label: "access routines: abstraction benefit",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["341-342"],
      label: "access routines: abstraction, level of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["339-340"],
      label: "access routines: advantages of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["339"],
      label: "access routines: barricaded variables benefit",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["339"],
      label: "access routines: centralized control from",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["340"],
      label: "access routines: creating",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["340"],
      label: "access routines: g_ prefix guideline",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["340"],
      label: "access routines: information hiding benefit",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["340-342"],
      label: "access routines: lack of support for, overcoming",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["341"],
      label: "access routines: locking",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["342"],
      label: "access routines: parallelism from",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["340"],
      label: "access routines: requiring",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["77-78"],
      label: "accidental problems",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["15-16"],
      label: "accreting a system metaphor",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["464"],
      label: "accuracy",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["63"],
      label: "Ada: description of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["174-175"],
      label: "Ada: parameter order",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["464"],
      label: "adaptability",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["104"],
      label: "Adapter pattern",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["295"],
      label: "addition, dangers of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["130"],
      label: "ADTs (abstract data types): abstraction with",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["339-342"],
      label: "ADTs (abstract data types): access routines",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["126-129"],
      label: "ADTs (abstract data types): benefits of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["128"],
      label: "ADTs (abstract data types): changes not propagating benefit",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["133"],
      label: "ADTs (abstract data types): classes based on",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["129-130"],
      label: "ADTs (abstract data types): cooling system example",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["126"],
      label: "ADTs (abstract data types): data, meaning of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["126"],
      label: "ADTs (abstract data types): defined",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["128"],
      label: "ADTs (abstract data types): documentation benefit",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["132"],
      label: "ADTs (abstract data types): explicit instancing",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["130"],
      label: "ADTs (abstract data types): files as",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["130-131"],
      label: "ADTs (abstract data types): guidelines",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["127"],
      label: "ADTs (abstract data types): hiding information with",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["132"],
      label: "ADTs (abstract data types): instancing",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["132"],
      label: "ADTs (abstract data types): implicit instancing",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["128"],
      label: "ADTs (abstract data types): interfaces, making more informative",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["130"],
      label: "ADTs (abstract data types): low-level data types as",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["131"],
      label: "ADTs (abstract data types): media independence with",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["131-133"],
      label: "ADTs (abstract data types): multiple instances, handling",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["126-127"],
      label: "ADTs (abstract data types): need for, example of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["131-133"],
      label: "ADTs (abstract data types): non-object-oriented languages, with",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["130"],
      label: "ADTs (abstract data types): objects as",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["129-130"],
      label: "ADTs (abstract data types): operations examples, table of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["128"],
      label: "ADTs (abstract data types): passing of data, minimization of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["126"],
      label: "ADTs (abstract data types): purpose of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["128-129"],
      label: "ADTs (abstract data types): real-world entities, working with",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["130"],
      label: "ADTs (abstract data types): representation question",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["131"],
      label: "ADTs (abstract data types): simple items as",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["128"],
      label: "ADTs (abstract data types): verification of code beneift",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["58", "658"],
      label: "agile development",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["630"],
      label: "algebraic identities",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["809"],
      label: "algorithms: commenting",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["12"],
      label: "algorithms: heuristics compared to",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["11-12"],
      label: "algorithms: metaphors serving as",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["607"],
      label: "algorithms: resources on",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["223"],
      label: "algorithms: routines, planning for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["311-316"],
      label: "aliasing",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["823"],
      label: "analysis skills development",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["58, 658"],
      label: "approaches to development: agile development",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["112-113", "697-698"],
      label: "approaches to development: bottom-up approaches",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["58", "471-472", "482", "708", "856"],
      label: "approaches to development: extreme programming",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["839-841"],
      label: "approaches to development: importance of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["See iteratino in development"],
      label: "approaches to development: iterative approach",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["840"],
      label: "approaches to development: premature optimization problem",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["840", "See also quality of software"],
      label: "approaches to development: quality control",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["58-59"],
      label: "approaches to development: resources for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["35-36"],
      label: "approaches to development: sequential approach",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["839-840"],
      label: "approaches to development: sequential approach",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["839-840"],
      label: "approaches to development: team processes",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["111-113", "694-696"],
      label: "approaches to development: top-down approaches",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["45"],
      label: "architecture: building block definition",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["46"],
      label: "architecture: business rules",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["51"],
      label: "architecture: buying vs. building components",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["44", "52"],
      label: "architecture: changes",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["54-55"],
      label: "architecture: checklist for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["46"],
      label: "architecture: class design",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["52"],
      label: "architecture: commitment delay strategy",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["52"],
      label: "architecture: conceptual integrity of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["46"],
      label: "architecture: data design",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["43"],
      label: "architecture: defined",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["49-50"],
      label: "architecture: error handling",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["50"],
      label: "architecture: fault tolerance",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["47"],
      label: "architecture: GUIs",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["44"],
      label: "architecture: importance of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["49"],
      label: "architecture: input/output",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["48"],
      label: "architecture: internationalization planning",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["48"],
      label: "architecture: interoperability",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["60"],
      label: "architecture: key points for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["48"],
      label: "architecture: localization planning",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["53"],
      label: "architecture: machine independence",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["51"],
      label: "architecture: overengineering",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["654-655"],
      label: "architecture: percent of total activity, by size of project",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["48"],
      label: "architecture: performance goals",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["590"],
      label: "architecture: performance-oriented",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["44"],
      label: "architecture: prerequisite nature of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["45-46"],
      label: "architecture: program organization",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["52-53", "55"],
      label: "architecture: quality",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["47"],
      label: "architecture: resource management",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["57"],
      label: "architecture: resources on developing",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["52"],
      label: "architecture: reuse decisions",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["53"],
      label: "architecture: risky areas, identifying",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["48"],
      label: "architecture: scalability",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["47"],
      label: "architecture: security design",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["51"],
      label: "architecture: technical feasibility",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["56"],
      label: "architecture: time allowed for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["47"],
      label: "architecture: user interface design",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["50"],
      label: "architecture: validation design",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["733"],
      label: "arithmetic expressions: misleading precedence example,",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["295"],
      label: "arithmetic expressions: magnitudes, greatly different",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["623-624"],
      label: "arithmetic expressions: multiplication, changing to addition",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["297"],
      label: "arithmetic expressions: rounding errors",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["311"],
      label: "arrays: C language macro for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["317"],
      label: "arrays: checklist",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["310"],
      label: "arrays: containers as an alternative",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["602"],
      label: "arrays: costs of operations",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["311"],
      label: "arrays: cross-talk",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["310"],
      label: "arrays: defined",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["625-626"],
      label: "arrays: dimensions, minimizing",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["310"],
      label: "arrays: end points, checking",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["372"],
      label: "arrays: foreach loops with",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["310-311"],
      label: "arrays: indexes of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["754"],
      label: "arrays: layout of references",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["387-388"],
      label: "arrays: loops with",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["310"],
      label: "arrays: multidimensional",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["280-281"],
      label: "arrays: naming conventions for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["593-594", "603-604"],
      label: "arrays: performance tuning",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["572"],
      label: "arrays: refactoring",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["626-627"],
      label: "arrays: references, minimizing",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["280-281"],
      label: "arrays: semantic prefixes for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["621-623"],
      label: "arrays: sentinel tests for loops",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["310"],
      label: "arrays: sequential access guideline",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["63"],
      label: "assmebly language: description of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["720"],
      label: "assmebly language: listing tools",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["640-642"],
      label: "assmebly language: recoding to",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["206"],
      label: "assertions: aborting program recommended",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["189"],
      label: "assertions: arguments for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["190"],
      label: "assertions: assumptions to check, list of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["205"],
      label: "assertions: barricades, relation to",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["189"],
      label: "assertions: benefits of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["191"],
      label: "assertions: building your own mechanism for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["191"],
      label: "assertions: C++ example",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["192"],
      label: "assertions: dangerous use of example",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["189"],
      label: "assertions: defined",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["350"],
      label: "assertions: dependencies, checking for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["191", "193-194"],
      label: "assertions: error handling with",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["191-192"],
      label: "assertions: executable code in",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["191-193"],
      label: "assertions: guidelines for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["190"],
      label: "assertions: Java example of",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["192-193"],
      label: "assertions: postcondition verification",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["192-193"],
      label: "assertions: precondition verification",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["190"],
      label: "assertions: removing from code",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["212"],
      label: "assertions: resource for",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["192-194"],
      label: "assertions: Visual Basic examples",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["249", "758"],
      label: "assignment statements",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["author role in inspections"],
      label: "486",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["333"],
      label: "auto_ptrs",
      title: "Code Complete",
    },
    {
      authors: ["Steve McConnell"],
      pages: ["528-529"],
      label: "automated testing",
      title: "Code Complete",
    },
    {
      authors: ["Eric Evans"],
      pages: ["435-437"],
      label: "Abstract Core",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["367"],
      label: "Adapters",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["126-127"],
      label: "Aggregates: definition",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["130-135", "170-171", "177-179"],
      label: "Aggregates: examples",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["128-129"],
      label: "Aggregates: invariants",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["127"],
      label: "Aggregates: local vs. global identity",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["125-129"],
      label: "Aggregates: overview",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["126"],
      label: "Aggregates: ownership relationships",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["483"],
      label: "Agile design: distillation",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["111"],
      label: "Agile design: Modules",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["265", "435-437", "463"],
      label: "Agile design: reducing dependencies",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["243-244", "260-264"],
      label: "Agile design: supple design",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["479"],
      label: "AIDS Memorial Quilt Project",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["47-49"],
      label: "Analysis models",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["See also design patterns"],
      label: "Analysis patterns",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["306-307"],
      label: "Analysis patterns: concept integrity",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["293"],
      label: "Analysis patterns: definition",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["295-306"],
      label: "Analysis patterns: example",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["294"],
      label: "Analysis patterns: overview",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["306-307"],
      label: "Analysis patterns: Ubiquitous Language",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["367"],
      label: "Anticorruption Layer: Adapters",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["368-369"],
      label: "Anticorruption Layer: considerations",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["369-370"],
      label: "Anticorruption Layer: examples",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["366-367"],
      label: "Anticorruption Layer: Facades",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["366-369"],
      label: "Anticorruption Layer: interface design",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["364-366"],
      label: "Anticorruption Layer: overview",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["384-385"],
      label: "Anticorruption Layer: relationships with external systems",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["70", "76-79"],
      label: "Application layer",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["70", "74", "156-157", "271-272", "495-496"],
      label: "Architectural frameworks",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["255-259"],
      label: "Assertions",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["102-103"],
      label: "Associations: bidirectional",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["169-170"],
      label: "Associations: example",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["82-88"],
      label: "Associations: for practical design",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["102-103"],
      label: "Associations: Value Objects",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["47"],
      label: "Astrolabe",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
    {
      authors: ["Eric Evans"],
      pages: ["210-216"],
      label: "Awkwardness, concept analysis",
      title:
        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
    },
  ]);

  return { indexEntries };
};
